# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # Code style
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    
    # Performance
    avoid_unnecessary_containers: true
    avoid_print: true
    
    # Best practices
    use_key_in_widget_constructors: true
    avoid_empty_else: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    unnecessary_const: true
    unnecessary_new: true
    
    # Documentation
    public_member_api_docs: false  # Optional: enable if you want documentation
    
    # Code quality
    avoid_dynamic_calls: true
    avoid_redundant_argument_values: true
    avoid_types_as_parameter_names: true
    cancel_subscriptions: true
    close_sinks: true
    no_duplicate_case_values: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

# Note: Hardcoded colors and text styles
# To find hardcoded colors and text styles, use:
# - grep -r "Color(0x" lib/
# - grep -r "Colors\." lib/ | grep -v "AppColors"
# - grep -r "TextStyle(" lib/ | grep -v "AppTypography"
# Always use AppColors and AppTypography from core/constants/
